# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  eliteapi:
    build:
      context: "G:\\Programming\\Elite"
      dockerfile: "EliteAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/EliteAPI.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/EliteAPI.staticwebassets.runtime.CT.json"
    image: "eliteapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\edmie\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https"
    - "G:\\Programming\\Elite\\EliteAPI:/app:rw"
    working_dir: "/app"
